# Generated by Django 6.0.5 on 2026-06-01 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Full name of the student', max_length=255)),
                ('phone_number', models.CharField(help_text="Student's contact phone number", max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('date_of_birth', models.DateField(help_text="Student's date of birth")),
                ('email', models.EmailField(help_text="Student's email address", max_length=254)),
                ('aadhar_number', models.CharField(help_text="Student's Aadhar number (12 digits)", max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('father_name', models.CharField(help_text="Father's full name", max_length=255)),
                ('father_number', models.CharField(help_text="Father's contact phone number", max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('mother_name', models.CharField(help_text="Mother's full name", max_length=255)),
                ('mother_number', models.CharField(blank=True, help_text="Mother's contact phone number (optional)", max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('address_line1', models.CharField(help_text='Street/House name', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Area/Landmark (optional)', max_length=255, null=True)),
                ('district', models.CharField(help_text='District name', max_length=100)),
                ('pincode', models.CharField(help_text='6-digit postal code', max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)])),
                ('course', models.CharField(choices=[('Arts', 'Arts'), ('Engineering', 'Engineering'), ('Nursing', 'Nursing'), ('Pharmacy', 'Pharmacy'), ('Allied Health Science', 'Allied Health Science'), ('Polytechnic', 'Polytechnic'), ('Law', 'Law'), ('Agriculture', 'Agriculture')], help_text='Selected course/discipline', max_length=100)),
                ('department_name', models.CharField(help_text='Department name for the selected course', max_length=255)),
                ('college', models.CharField(choices=[('Dhanalakshmi Srinivasan University', 'Dhanalakshmi Srinivasan University'), ('Saveetha University', 'Saveetha University')], help_text='Selected college', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the application was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the application was last updated')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Application review status', max_length=20)),
            ],
            options={
                'verbose_name': 'Scholarship Application',
                'verbose_name_plural': 'Scholarship Applications',
                'db_table': 'scholarship_applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
